add content auto Automatic Variables and Wildcards

diff --git a/_posts/2025-07-23-Makefile.md b/_posts/2025-07-23-Makefile.md
--- a/_posts/2025-07-23-Makefile.md
+++ b/_posts/2025-07-23-Makefile.md
@@ -131,7 +131,7 @@ all:
 ## Targets
 ### The all target
 #### VD:
-Tao ra nhieu target nhung chay chung cung 1 luc 
+Tạo ra nhiều target nhưng chạy chung cùng một lúc.
 ```makefile
 all: one two three
 
@@ -153,11 +153,99 @@ all: f1.o f2.o
 f1.o f2.o:
 	echo $@
 ```
-ket qua chay laf
+Kết quả chạy là:
 ```makefile
  ⚡loo ❯❯ make all
 echo f1.o
 f1.o
 echo f2.o
 f2.o
+```
+## Automatic Variables and Wildcards
+### Wildcard
+Cả hai ** * ** và ** % ** gọi là wildcards trong Make, nhưng hai cái có ý nghĩa khác nhau. ** * ** tìm kiếm file trong hệ thống của bạn giống tên filenames.
+
+### * Wildcard
+Phải bọc nó trong hàm wildcard, bởi vì sẽ dính một lỗi phổ biến dưới đây.
+```makefile
+# Print out file information about every .c file
+print: $(wildcard *.c)
+	ls -la  $?
+```
+Không dùng trong lúc định nghĩa biến
+##### VD:
+```makefile
+SRC = *.c
+```
+Nếu không có file .c nào trong thư mục thì nó sẽ giữ nguyên và hiểu là chuỗi *.c, cho nên nên dùng hàm **wildcard**.
+
+```makefile
+thing_wrong := *.o # Don't do this! '*' will not get expanded
+thing_right := $(wildcard *.o)
+
+all: one two three four
+
+# Fails, because $(thing_wrong) is the string "*.o"
+one: $(thing_wrong)
+
+# Stays as *.o if there are no files that match this pattern :(
+two: *.o 
+
+# Works as you would expect! In this case, it does nothing.
+three: $(thing_right)
+
+# Same as rule three
+four: $(wildcard *.o)
+```
+### % Wildcard
+Dấu % thật sự rất hữu ích, nhưng hơi gây nhầm lẫn vì nó có thể được sử dụng trong nhiều tình huống khác nhau.
+- Khi dùng ở chế độ "so khớp" (matching), ** % ** sẽ khớp với một hoặc nhiều ký tự trong một chuỗi. Phần chuỗi khớp này được gọi là stem (thân chuỗi).
+```makefile
+%.o: %.c
+	gcc -c $< -o $@
+```
+Ở đây:
+
+** % ** khớp với phần stem là main
+
+** % ** trong %.o nghĩa là main.o
+
+** % **  trong %.c nghĩa là main.c
+
+- Khi dùng ở chế độ "thay thế" (replacing), ** % **sẽ lấy phần stem đã khớp được và thay thế nó vào chuỗi khác.
+```makefile
+SRC = main.c utils.c math.c
+OBJ = $(patsubst %.c, %.o, $(SRC))
+```
+Kết quả:
+```makefile
+OBJ = main.o utils.o math.o
+```
+- ** % ** thường được dùng nhất trong định nghĩa rule (luật/phép xây dựng) và trong một số hàm đặc biệt.
+
+### Automatic Variables
+```makefile
+hey: one two
+	# Outputs "hey", since this is the target name
+	echo $@
+
+	# Outputs all prerequisites newer than the target
+	echo $?
+
+	# Outputs all prerequisites
+	echo $^
+
+	# Outputs the first prerequisite
+	echo $<
+
+	touch hey
+
+one:
+	touch one
+
+two:
+	touch two
+
+clean:
+	rm -f hey one two
 ```
